### ISSUE TITLE
Admin: Create a new meetup

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#22]
## User Story
As an admin user, I would like to create a new meetup.

## Notes
This ticket requires multiple steps:
- [x] Creating a `Admin::EventsController#create` controller action that creates a new event from the provided params
  - [ ] This action should also validate that there is a `current_user` and redirect to the site homepage if no user is logged in.
- [x] Creating a Rails view with a form where an admin user can enter information about the new event and save it
  - [ ] If the provided information does not create a valid event, errors should be displayed on the corresponding form fields or in a banner at the top of the page.

**Comment by ty18881** [comment]
I hahve some free time coming up.  I'm happy to work on this task.

**Comment by egiurleo** [comment]
Awesome, thanks @ty18881!

**Comment by egiurleo** [comment]
@marieusha Is working on this (will assign once the permissions are set up properly).

**Comment by luciagirasoles** [comment]
Hi @marieusha. Is there any way we might assist you with this requirement? You've been assigned to this ticket for quite some time; please have a look at it soon or let me know so that I may un-assign you. If you ever want to try working on it again in the future, I’m happy to re-assign you, I just want to make room for other people to work on it if they want to.
