### ISSUE TITLE
Paginate jobs page

### ISSUE THREAD

**Issue by egiurleo** [wnbrb/wnb-rb-site#90]
The jobs page currently has no pagination. This is not an issue yet because there are not that many jobs, but once we get above ~25 jobs, it would be good to have pagination.

Success criteria for this ticket:
- [ ] Add a `page` parameter to the `/api/jobs` endpoint that only returns 25 jobs offset by the number of pages
- [ ] Create a pagination UI in the frontend
- [ ] Use that UI to send the parameter to the backend and only display the relevant jobs

**Comment by emmabeynon** [comment]
Would you consider using a gem like [Pagy](https://github.com/ddnexus/pagy) to handle pagination?  It's fast, easy to implement and handles a lot of the potential pitfalls that come with developing your own pagination solution.

**Comment by egiurleo** [comment]
Oh @emmabeynon that's smart! I've never used it before but would be in favor of offloading this behavior onto a gem.

**Comment by emmabeynon** [comment]
@egiurleo Great 👍🏻 We use it in our app at work, it's super simple.  I'm happy to take this issue; can't seem to assign myself to it though.

**Comment by egiurleo** [comment]
@emmabeynon assigned! Thanks for taking it 💕

**Comment by luciagirasoles** [comment]
Hi @emmabeynon. Is there any way we might assist you with this requirement? You've been assigned to this ticket for quite some time; please have a look at it soon or let me know so that I may un-assign you. If you ever want to try working on it again in the future, I’m happy to re-assign you, I just want to make room for other people to work on it if they want to.

**Comment by luciagirasoles** [comment]
job board has been closed for the moment
